const exampleXml =  `<Keyboard>
<Name>OptiKey-BoardMaker</Name>
<Height>40</Height>
<SymbolMargin>1</SymbolMargin>
<BorderThickness>0,0,0,0</BorderThickness>
<Grid>
  <Rows>7</Rows>
  <Cols>12</Cols>
</Grid>
<Content>
  <DynamicKey>
    <Row>0</Row>
    <Col>7</Col>
    <Text>7</Text>
    <Label>7</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>8</Col>
    <Text>8</Text>
    <Label>8</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>9</Col>
    <Text>9</Text>
    <Label>9</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>0</Col>
    <Text>\\</Text>
    <Label>\\</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>0</Col>
    <Text>~</Text>
    <Label>~</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>10</Col>
    <Text>$</Text>
    <Label>$</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>6</Col>
    <Text>&amp;</Text>
    <Label>&amp;</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>11</Col>
    <Text>^</Text>
    <Label>^</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>1</Col>
    <Text>!</Text>
    <Label>!</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>2</Col>
    <Text>?</Text>
    <Label>?</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>11</Col>
    <Text>|</Text>
    <Label>|</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>4</Col>
    <Text>4</Text>
    <Label>4</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>5</Col>
    <Text>5</Text>
    <Label>5</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>6</Col>
    <Text>6</Text>
    <Label>6</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>0</Col>
    <Text>/</Text>
    <Label>/</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>3</Col>
    <Text>:</Text>
    <Label>:</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>5</Col>
    <Text>f</Text>
    <ShiftUpLabel>f</ShiftUpLabel>
    <ShiftDownLabel>F</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>6</Col>
    <Text>g</Text>
    <ShiftUpLabel>g</ShiftUpLabel>
    <ShiftDownLabel>G</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>7</Col>
    <Text>h</Text>
    <ShiftUpLabel>h</ShiftUpLabel>
    <ShiftDownLabel>H</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>1</Col>
    <Text>q</Text>
    <ShiftUpLabel>q</ShiftUpLabel>
    <ShiftDownLabel>Q</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>8</Col>
    <Text>j</Text>
    <ShiftUpLabel>j</ShiftUpLabel>
    <ShiftDownLabel>J</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>5</Col>
    <Text>%</Text>
    <Label>%</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>1</Col>
    <Text>1</Text>
    <Label>1</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>2</Col>
    <Text>2</Text>
    <Label>2</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>8</Col>
    <Text>m</Text>
    <ShiftUpLabel>m</ShiftUpLabel>
    <ShiftDownLabel>M</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>7</Col>
    <Text>n</Text>
    <ShiftUpLabel>n</ShiftUpLabel>
    <ShiftDownLabel>N</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>10</Col>
    <Text>p</Text>
    <ShiftUpLabel>p</ShiftUpLabel>
    <ShiftDownLabel>P</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>6</Col>
    <Text>b</Text>
    <ShiftUpLabel>b</ShiftUpLabel>
    <ShiftDownLabel>B</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>9</Col>
    <Text>k</Text>
    <ShiftUpLabel>k</ShiftUpLabel>
    <ShiftDownLabel>K</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>5</Col>
    <Text>v</Text>
    <ShiftUpLabel>v</ShiftUpLabel>
    <ShiftDownLabel>V</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>0</Col>
    <Text>-</Text>
    <Label>-</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>3</Col>
    <Text>3</Text>
    <Label>3</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>1</Col>
    <Text>_</Text>
    <Label>_</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>2</Col>
    <Text>;</Text>
    <Label>;</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>9</Col>
    <Text>@</Text>
    <Label>@</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>7</Col>
    <Text>"</Text>
    <Label>"</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>8</Col>
    <Text>'</Text>
    <Label>'</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>11</Col>
    <Text>#</Text>
    <Label>#</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>10</Col>
    <Text>0</Text>
    <Label>0</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>10</Col>
    <Text>l</Text>
    <ShiftUpLabel>l</ShiftUpLabel>
    <ShiftDownLabel>L</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>3</Col>
    <Text>s</Text>
    <ShiftUpLabel>s</ShiftUpLabel>
    <ShiftDownLabel>S</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>4</Col>
    <Text>r</Text>
    <ShiftUpLabel>r</ShiftUpLabel>
    <ShiftDownLabel>R</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>5</Col>
    <Text>t</Text>
    <ShiftUpLabel>t</ShiftUpLabel>
    <ShiftDownLabel>T</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>4</Col>
    <Text>c</Text>
    <ShiftUpLabel>c</ShiftUpLabel>
    <ShiftDownLabel>C</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>4</Col>
    <Text>d</Text>
    <ShiftUpLabel>d</ShiftUpLabel>
    <ShiftDownLabel>D</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>2</Col>
    <Text>w</Text>
    <ShiftUpLabel>w</ShiftUpLabel>
    <ShiftDownLabel>W</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>3</Col>
    <Text>+</Text>
    <Label>+</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>1</Col>
    <Text>&lt;</Text>
    <Label>&lt;</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>10</Col>
    <Text>=</Text>
    <Label>=</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>3</Row>
    <Col>2</Col>
    <Text>a</Text>
    <ShiftUpLabel>a</ShiftUpLabel>
    <ShiftDownLabel>A</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>3</Col>
    <Text>e</Text>
    <ShiftUpLabel>e</ShiftUpLabel>
    <ShiftDownLabel>E</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>8</Col>
    <Text>i</Text>
    <ShiftUpLabel>i</ShiftUpLabel>
    <ShiftDownLabel>I</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>9</Col>
    <Text>o</Text>
    <ShiftUpLabel>o</ShiftUpLabel>
    <ShiftDownLabel>O</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>7</Col>
    <Text>u</Text>
    <ShiftUpLabel>u</ShiftUpLabel>
    <ShiftDownLabel>U</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>3</Col>
    <Text>x</Text>
    <ShiftUpLabel>x</ShiftUpLabel>
    <ShiftDownLabel>X</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>2</Col>
    <Text>y</Text>
    <ShiftUpLabel>y</ShiftUpLabel>
    <ShiftDownLabel>Y</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>2</Row>
    <Col>6</Col>
    <Text>z</Text>
    <ShiftUpLabel>z</ShiftUpLabel>
    <ShiftDownLabel>Z</ShiftDownLabel>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>1</Col>
    <Text>&gt;</Text>
    <Label>&gt;</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>2</Col>
    <Text>,</Text>
    <Label>,</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>3</Col>
    <Text>.</Text>
    <Label>.</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>4</Col>
    <Text>(</Text>
    <Label>(</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>5</Col>
    <Text>)</Text>
    <Label>)</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>6</Col>
    <Text>[</Text>
    <Label>[</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>7</Col>
    <Text>]</Text>
    <Label>]</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>8</Col>
    <Text>{</Text>
    <Label>{</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>9</Col>
    <Text>}</Text>
    <Label>}</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>4</Row>
    <Col>0</Col>
    <Symbol>TabIcon</Symbol>
    <useSymbol>true</useSymbol>
    <Text>&#9;</Text>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>5</Col>
    <Width>2</Width>
    <Symbol>SpaceIcon</Symbol>
    <Text>&#32;</Text>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>7</Col>
    <Symbol>EnterIcon</Symbol>
    <Text>&#13;</Text>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>9</Col>
    <Text>\`</Text>
    <Label>\`</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>1</Row>
    <Col>4</Col>
    <Text>*</Text>
    <Label>*</Label>
  </DynamicKey>
  <DynamicKey>
    <Row>0</Row>
    <Col>11</Col>
    <Symbol>MenuIcon</Symbol>
    <Action>MenuKeyboard</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>8</Col>
    <Symbol>BackOneIcon</Symbol>
    <Action>BackOne</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>0</Col>
    <Label>Win</Label>
    <Action>LeftWin</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>10</Col>
    <Symbol>UpArrowKeyIcon</Symbol>
    <Action>ArrowUp</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>5</Row>
    <Col>11</Col>
    <Label>Esc</Label>
    <Action>Escape</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>0</Col>
    <Label>Ctrl</Label>
    <Action>LeftCtrl</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>1</Col>
    <Label>Alt</Label>
    <Action>LeftAlt</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>4</Col>
    <Symbol>ShiftIcon</Symbol>
    <Action>LeftShift</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>9</Col>
    <Symbol>LeftArrowKeyIcon</Symbol>
    <Action>ArrowLeft</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>10</Col>
    <Symbol>DownArrowKeyIcon</Symbol>
    <Action>ArrowDown</Action>
  </DynamicKey>
  <DynamicKey>
    <Row>6</Row>
    <Col>11</Col>
    <Symbol>RightArrowKeyIcon</Symbol>
    <Action>ArrowRight</Action>
  </DynamicKey>
</Content>
</Keyboard>`

export default exampleXml
